### PR TITLE
Cartesian column max width

### PR DESCRIPTION
**Pull request by anandtiwary**
## Description
Please include a summary of the change, motivation and context.
fix: reducing max width of Cartesian column

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### Documentation
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

### CODE REVIEW

**Review by aaron-steinfeld — COMMENTED** [review]
Context? this is a major styling change on the bar chart and there's no explanation here. This would be especially egregious on a time series where a skinny bar wouldn't align with the time bucket it represents.

image

**Comment by aaron-steinfeld** [comment]
> The chart in the screenshot above shouldn't be affected by this change. The alignment is also calculated based on the column width, so it wouldn't go wrong either.

That screenshot is just the UI with this change - certainlyaffected. The alignment of the left side (origin) of the bar is correct, aligning with the start of the interval but now the bar only extends for the shorter width.

> A higher column width when more space is available is a UX preference. The recent UX preference is to show a skinner chart even when more space is present.

Agreed at the end of the day it's a preference. If we're changing this everywhere though (which we are) did we take all the various usages into consideration when changing this - time series with bars, grouped time series, plain bar charts without time? Larger charts and smaller? Or is this based on one particular mock/screen? If we only want it one place, we should just make it configurable.

**Comment by anandtiwary** [comment]
I have checked it at a few other places and it seems fine to me. And I remember when I originally wrote this code, I played around with this variable a lot and ensured changing it would not affect any other chart logic as such. At that time, I looked into Highcharts and kept their behavior (fat columns if more space is available). 


> That screenshot is just the UI with this change - certainlyaffected. The alignment of the left side (origin) of the bar is correct, aligning with the start of the interval but now the bar only extends for the shorter width.

So, this is not a problem, right? We do an origin x adjustment too which tries to align the column center at the interval (unless there are grouped series)

```
  private getOriginXAdjustment(columnWidth: number): number {
    const totalGroupedSeries = this.xScale.getGroupedColumnSeriesLength(this.series);
    const groupedColumnAdjustment = (this.xScale.getBandwidth() - columnWidth * totalGroupedSeries) / 2;

    return totalGroupedSeries === 1
      ? groupedColumnAdjustment
      : groupedColumnAdjustment + this.xScale.getGroupedColumnSeriesPosition(this.series) * columnWidth;
  }
```

**Comment by aaron-steinfeld** [comment]
> So, this is not a problem, right? We do an origin x adjustment too which tries to align the column center at the interval (unless there are grouped series)

I guess a matter of opinion. Let me try and grab screens of each for comparison. To me, that's just an awful lot of whitespace in the narrower versions:

narrow/time series:
image
narrow/grouped time series:
image
narrow/grouped:
image

current/time series:
image

current/grouped time series:
image

current/grouped:
image

**Comment by anandtiwary** [comment]
Yeah, there is a lot of white-space. How do we make a decision here? UX team has to own it and this is what I got from them.

**Comment by anandtiwary** [comment]
Closing this for now.

**Pull request closed without merging**
