### PR TITLE
fix: stop syncing explorer page data to url

### PR DESCRIPTION
**Pull request by aaron-steinfeld**

### CODE REVIEW

**Review by skjindal93 — APPROVED** [review]

**Comment by anandtiwary** [comment]
Wouldn't this break the filtering ? cc @jake-bassett

**Comment by aaron-steinfeld** [comment]
> Wouldn't this break the filtering ? cc @jake-bassett 

Filters are still part of the url, this takes out paging and sort data

**Comment by anandtiwary** [comment]
And why are we taking them out?

**Comment by aaron-steinfeld** [comment]
> And why are we taking them out?

This isn't actually a full screen dashboard for one. As a consequence there's a bug where, if changing the dashboard filters when on the second page of data, the new data is fetched but the page is not reset. We still need to fix this for full page tables I suspect (depends on how they react to a new data source) but this change gets the most problematic spot and seems right regardless

**Comment by anandtiwary** [comment]
okay

**Pull request merged**
